language: python

cache: pip
  directories:
  - $HOME/.extinction/maps/

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy nose matplotlib astropy seaborn pyyaml requests pytest
  - source activate test-environment
  - pip install codecov
  - pip install coveralls
  - pip install healpy
  - pip install astroquery
  - pip install sncosmo
  - pip install wget
  - python setup.py install
  
# command to run tests
script:
  - coverage run --source="./" setup.py test
  - coverage run -a --source="./" extinction/*py
  - coverage run -a --source="./" extinction/extern/*py
  - coverage run -a --source="./" scripts/*.py
  - get_maps.py
after_success:
  - codecov
  - coveralls

